### PR TITLE
Added terms and privacy policy

### PR DESCRIPTION
**Pull request by Manveer695**
Fixes issue #51 i.e. Terms and privacy policy required for the SUSI FBbot.

### CODE REVIEW

**Comment by Manveer695** [comment]
@AliAyub007 @madhavrathi @saurabhjn76 Please review it. Thanks.

**Comment by mariobehling** [comment]
Why do we need this here?  Please use the privacy link to the susi ai chat service.

**Comment by Manveer695** [comment]
@mariobehling Sir, our Susi chat privacy link does not support https. The Facebook guidelines need the privacy URL to support https. We can get that support from Github. Thank you.

**Comment by mariobehling** [comment]
We cannot maintain different privacy sites for each repo. Please help to make https work for chat.susi.ai.

**Comment by Manveer695** [comment]
Ok, will use the chat.susi.ai privacy link. Thanks.

**Pull request closed without merging**
