### PR TITLE
Update SUSI API

### LINKED ISSUE #72: Update SUSI API
**Actual Behaviour**

SUSI API is outdated.

**Expected Behaviour**

API should be updated.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by DNS-404**
Fixes #72 

Changes: Updated SUSI API to `https://api.susi.ai/susi/chat.json`

### CODE REVIEW

**Comment by AliAyub007** [comment]
@DNS-404 Make sure all the tests pass on your commit.

**Comment by DNS-404** [comment]
@AliAyub007 Okay. I'll look into it.

**Comment by AliAyub007** [comment]
@DNS-404 Frequently mention your fellows to review your PRs using @ feature.

**Comment by DNS-404** [comment]
Okay. Sorry, you had to tell me this again. 😓
@hkedia321 @anshumanv @Akshat-Jain @PrP-11 Please review.

**Comment by DNS-404** [comment]
@AliAyub007 Please review

**Pull request merged**
